name: PostOffice
api-version: 1.15
version: '${project.version}'
author: Shantek.io
main: io.shantek.PostOffice

commands:
  postoffice:
    description: Reload the PostOffice plugin
    usage: /postoffice reload
    permission: shantek.postoffice.reload
    default: op